language: 
  - java

jdk:
  - oraclejdk8
  
script:
  - gradle build jacocoTestReport
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
  
  jobs:
  include:
    - stage: test
      script: ./test 1
    - # stage name not required, will continue to use `test`
      script: ./test 2
    - stage: deploy
      script: ./deploy
